### ISSUE TITLE
Order History 

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#12]
1. After cancelling the order it is showing transaction cancelled by user page, here showing Order History tab and click on order history tab there is no change in the order history so no need to show that tab.
![pa8](https://user-images.githubusercontent.com/20244174/32607995-c71a68ae-c580-11e7-89b7-3e51f9d9e61d.png)

2. After placing the order using any payment method showing order successful page with order history tab, click on order history tab it is navigating to my orders - Wallet History page. Actually it should show orders - Shopping page. Please check.
![pa9](https://user-images.githubusercontent.com/20244174/32608001-cd467e70-c580-11e7-9249-4b9a3559c758.png)

**Comment by rajesh-uragonda** [comment]
1. When  an order is canceled by user, Order History at the bottom is now hidden as suggested.
2. Made changes to the Navigation, when a you make a successful shopping order, you will be navigated to Shopping Orders Page, when you successfully Added Money and Sent Money, you will be navigated to Wallet History page. When bills are successfully paid, you will be navigated to Recharge & Bills History.

**Comment by babymercy** [comment]
Working fine.
Issue fixed.
