### ISSUE TITLE
App Crash - Order History

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#13]
After placing the order or cancelling the order then click on order history app got crashed at my orders page while loading. Unable to reproduce, check this.
![image](https://user-images.githubusercontent.com/20244174/32609112-853381ec-c584-11e7-9389-c677b2dbbd99.png)

**Comment by rajesh-uragonda** [comment]
I am unable to produce this crash, I have handled code in the api call but not sure it is the reason for the crash.

**Comment by babymercy** [comment]
Checked this issue not getting app crash working fine.
Issue fixed.
