### ISSUE TITLE
Wallet and COD 

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#14]
Using payment methods - wallet with COD >
Placed order using wallet amount and COD with RS. 4 wallet amount and reaming amount with COD , check in the below screenshot.
![image](https://user-images.githubusercontent.com/20244174/32646033-763aaed6-c610-11e7-8b17-252d3eb51f78.png)
Order got successful with the amount Rs.4 only means total amount showing Rs. 4 at order history and invoice pages.
![image](https://user-images.githubusercontent.com/20244174/32646137-189d2118-c611-11e7-8697-4d3fcdb3425d.png)
![image](https://user-images.githubusercontent.com/20244174/32646139-216d966a-c611-11e7-9c70-6b7b5c032ddf.png)

**Comment by babymercy** [comment]
Issue not fixed.
![pa12](https://user-images.githubusercontent.com/20244174/32780155-4c2218e2-c966-11e7-873a-76a864dd325c.png)
![pa13](https://user-images.githubusercontent.com/20244174/32780165-536f8c7e-c966-11e7-9aaf-43fd6486c1a6.png)
![pa14](https://user-images.githubusercontent.com/20244174/32780168-59561d10-c966-11e7-980a-ff2a8ddc5c80.png)

**Comment by babymercy** [comment]
Showing correct total price details at all pages but still having doubt on 
1. Reference column and Tax Rate column in the invoice details page > Getting empty columns.
2. We have delivery address functionality only but showing delivery address as billing address in the order confirmation email and Invoices.

Please check these two functionalities in the both **Android and Web** applications of both order confirmation emails and invoices details.

**Comment by ashiya-syed** [comment]
check now

**Comment by babymercy** [comment]
1. and 2. > Removed Reference, Tax rate columns and Billing address details from order confirmation and invoice details pages.
Issue fixed.
