### ISSUE TITLE
Emails from Pay2Cart

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#15]
Check all these emails:
1. Password query confirmation email to reset password.
2. Order process and Order confirmation emails after order placing for all payment methods.
3. Send amount to User - 
a) To Sender - Order successful email.
b) To Receiver - After sending money to any user we are not sending any email / message to that receiver.
4. Vouchers email - After getting any voucher for particular order.

These emails are not getting for Android application from Pay2Cart.

**Comment by ashiya-syed** [comment]
1.Password query confirmation email to reset password is working fine.
2.Order process and Order confirmation emails after order placing for all payment methods are working now.

**Comment by babymercy** [comment]
Yes, getting password query and order confirmation emails.

**Comment by babymercy** [comment]
Vouchers functionality mentioned in 11th missing functionalities issue > This functionality will implement in the **version 2.0.**

3. b) - Send amount to User - After sending money to any user we are not sending any email / message to that receiver > Please check this issue in both **Android and Web** applications.
Implement this functionality if it is required.

**Comment by babymercy** [comment]
3. b) > Got confirmation from developers.
