### ISSUE TITLE
Search - App Crash

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#2]
Search Functionality > Enter special characters input in the search bar then click on search icon from keyboard it leads to app crash.
![image](https://user-images.githubusercontent.com/20244174/32533041-4a917abe-c474-11e7-8340-fe9aac206cb1.png)

**Comment by rajesh-uragonda** [comment]
1. Implemented the functionality as suggested.
# Search keyword will be saved only if we have results for the search word.
# UI - search keyword is set to single line.

2. Am able to get products by giving a brand name Ex: navratna, may be for few we may be not getting the result. @ashiya-syed  once can you check the search api.

**Comment by babymercy** [comment]
1. Search Key Words - **Issue Fixed**.
2. Search functionality - Not getting search results for few products.

**Comment by rajesh-uragonda** [comment]
@ashiya-syed  once can you check the search api 
>if we search for products by giving the exact product name only for few products we are getting the results.

**Comment by babymercy** [comment]
Working fine, issue fixed.
