### ISSUE TITLE
Shop by Category and New Arrivals Block

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#5]
1. Shop by Category Block >
a) UI - All categories names showing capital letters except **household** category.
b) Not getting full name for few sub categories.
c) Few subcategories > Not getting icons for few subcategories.
![pa1](https://user-images.githubusercontent.com/20244174/32537689-84498976-c489-11e7-9374-89e73ea40ff4.png)
d) Not getting all sub categories as compared to Pay2Cart website.

2. New Arrivals Block > Click on "OLYMPIA SPACE RACE GAME" product got "Exception Occurred, please try again" error.
![image](https://user-images.githubusercontent.com/20244174/32541834-dd018e44-c496-11e7-8c73-1f3492c5ecd0.png)

**Comment by babymercy** [comment]
1 > a), b), c) and 2nd Issues are fixed, 1 - d) but not getting PERSONAL CARE - PERSONAL HYGIENE sub category.

**Comment by ashiya-syed** [comment]
check now

**Comment by babymercy** [comment]
Fixed.
