### ISSUE TITLE
Product Details Page - Functionalities

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#7]
Product Details Page > 
Review, Check Availability, Print, Send to a Friend, Available Items, Share to social links and Reviews block to view the sent reviews functionalities - These functionalities not provided in the android application???

**Comment by babymercy** [comment]
Share Functionality > Provided share functionality in the product details page, When I shared to any link It's producing the another "Products from same category" block for every sharing.
![pa11](https://user-images.githubusercontent.com/20244174/32777102-f52a7e72-c95a-11e7-83d4-d87870dcec04.png)

**Comment by rajesh-uragonda** [comment]
Resolved issue when using Share Functionality.

**Comment by babymercy** [comment]
Share Functionality - Products from same category - **Issue fixed**.

Product Details Page - Provided share, available items and check availability functionalities.

**Comment by babymercy** [comment]
Provided all above mentioned functionalities.
Issue fixed.
