### ISSUE TITLE
Product Details Page - UI

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#8]
Product Details Page > 
1. Check the horizontal slider buttons at the product image.
![pa2](https://user-images.githubusercontent.com/20244174/32544555-cfcea02e-c49e-11e7-9ffc-82b0aea3b0db.png)

2. Showing horizontal slider button even products having one image also.
![pa3](https://user-images.githubusercontent.com/20244174/32544652-21e86fca-c49f-11e7-8c99-79e446b78a97.png)

3. Check the empty space at below the products from same category block.
![pa4](https://user-images.githubusercontent.com/20244174/32544768-85b35a42-c49f-11e7-9119-e2cbc8990387.png)

**Comment by rajesh-uragonda** [comment]
The number of Horizontal slider dots displayed will be equal to the number of product images we are receiving from the api, please let me know if we need to hide when image is one.

**Comment by babymercy** [comment]
Yes we need to hide the horizontal slider dots, because if we are showing one image for any product no need of horizontal slider dots.

**Comment by babymercy** [comment]
Issue fixed.
