### ISSUE TITLE
Menu - Shopping - Categories

### ISSUE THREAD

**Issue by babymercy** [webet/Pay2Cart-Andriod-NEW#9]
Menu - Shopping - Categories > 
Click on shopping tab at menu it is showing categories, here it should show all main categories list only but it is showing few sub categories also, all main categories showing capital letter except "household" and when we click on any category it is not showing related icons for few sub categories.
![pa5](https://user-images.githubusercontent.com/20244174/32546725-065259c2-c4a6-11e7-90ec-28e600bdedbc.png)
![image](https://user-images.githubusercontent.com/20244174/32546747-119a0488-c4a6-11e7-8667-b11c07885bcb.png)
![pa6](https://user-images.githubusercontent.com/20244174/32546786-2f9f3796-c4a6-11e7-831b-3fc0cf084c31.png)

**Comment by rajesh-uragonda** [comment]
These are coming from Api, so it can resolved from the back end itself.

**Comment by babymercy** [comment]
1. There is a duplicate category.
![pa10](https://user-images.githubusercontent.com/20244174/32710819-48483694-c861-11e7-8adc-4249a6185510.png)
2. Follow the same format for sub categories names.
3. There is a duplicate(ARTIFICIAL JEWELRY) sub category in the WOMEN category.
4. Not getting "Personal Hygiene" sub category in the PERSONAL CARE category.
5. Need confirmation on the sub categories icon.

**Comment by babymercy** [comment]
All Issues are fixed except BABY & KIDS duplicate category.
Please check this also.

**Comment by ashiya-syed** [comment]
check now

**Comment by babymercy** [comment]
Fixed.
